spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
