spring:
  #  datasource:
  #    url: jdbc:h2:mem:todayshobby
  #    driverClassName: org.h2.Driver
  #    username: sa
  #    password:
  #  h2:
  #    console:
  #      enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todayshobby
    username: todayshobby
    password: 1234
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/todayshobby
#    user: todayshobby
#    password: 1234
#    locations: classpath:db/migration
